encryption_config: |
  kind: EncryptionConfig
  apiVersion: v1
  resources:
    - resources:
        - secrets
      providers:
        - identity: {}
        - aescbc:
            keys:
              - name: key1
                secret: $(head -c 32 /dev/urandom | base64)
