---
- name: kube-proxy directory
  file:
    path: /var/lib/kubernetes
    state: directory

- name: kube-proxy service file
  template:
    src: kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service
    mode: 0644

- name: copy certs
  copy:
    remote_src: yes
    src: "{{ kubernetes.pki.path }}/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
  with_items:
    - ca.pem
    - kube-proxy.pem
    - kube-proxy-key.pem

- name: copy kubeconfig
  copy:
    remote_src: yes
    src: "{{ kubernetes.conf.path }}/kube-proxy.kubeconfig"
    dest: /var/lib/kubernetes/kube-proxy.kubeconfig

- name: Start kube-proxy service
  systemd:
    name: kube-proxy
    daemon_reload: yes
    enabled: yes
    state: restarted
