---
- name: download etcd
  get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/{{ kubernetes.versions.etcd }}/etcd-{{ kubernetes.versions.etcd }}-linux-amd64.tar.gz"
    dest: "/tmp/etcd-{{ kubernetes.versions.etcd }}-linux-amd64.tar.gz"
  retries: 3
  delay: 1

- name: unpack etcd binary
  unarchive:
    src: "/tmp/etcd-{{ kubernetes.versions.etcd }}-linux-amd64.tar.gz"
    dest: /tmp
    creates: "/tmp/etcd-{{ kubernetes.versions.etcd }}-linux-amd64"

- name: create /usr/local/bin
  file:
    path: /usr/local/bin
    state: directory
    mode: 0755

- name: copy etcd[ctl] binary to /usr/local/bin
  copy:
    remote_src: yes
    src: "/tmp/etcd-{{ kubernetes.versions.etcd }}-linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - etcd
    - etcdctl
