---
- name: kube-controller-manager directory
  file:
    path: /var/lib/kubernetes
    state: directory

- name: kube-controller-manager service file
  template:
    src: kube-controller-manager.service
    dest: /etc/systemd/system/kube-controller-manager.service
    mode: 0644
    owner: etcd

- name: copy certs
  copy:
    remote_src: yes
    src: "{{ kubernetes.pki.path }}/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
  with_items:
    - ca.pem
    - ca-key.pem
    - service-account-key.pem

- name: copy kubeconfig
  copy:
    remote_src: yes
    src: "{{ kubernetes.conf.path }}/kube-controller-manager.kubeconfig"
    dest: /var/lib/kubernetes/kube-controller-manager.kubeconfig


- name: Start kube-controller-manager service
  systemd:
    name: kube-controller-manager
    daemon_reload: yes
    enabled: yes
    state: restarted
