- name: Generate kube-api-server private key
  openssl_privatekey:
    path: '{{ kubernetes.pki.path }}/kubernetes-key.pem'

- name: Generate kube-api-server CSR
  openssl_csr:
    path: '{{ kubernetes.pki.path }}/kubernetes.csr'
    privatekey_path: '{{ kubernetes.pki.path }}/kubernetes-key.pem'
    basic_constraints: "CA:FALSE"
    basic_constraints_critical: True
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: True
    extended_key_usage:
      - serverAuth
      - clientAuth
    common_name: k8s-kubernetes
    organization_name: "system:masters"
    organizational_unit_name: k8s the hard way
    subject_alt_name: "DNS:kubernetes.default,IP:127.0.0.1,IP:{{ kubernetes.network.public.ipv4 }},IP:{{ kubernetes.network.public.ipv6 }}"

- name: Generate kube-api-server certificate
  openssl_certificate:
    path: '{{ kubernetes.pki.path }}/kubernetes.pem'
    csr_path: '{{ kubernetes.pki.path }}/kubernetes.csr'
    ownca_path: '{{ kubernetes.pki.path }}/ca.pem'
    ownca_privatekey_path: '{{ kubernetes.pki.path }}/ca-key.pem'
    provider: ownca
