
- name: Generating Kube Proxy private key
  openssl_privatekey:
    path: '{{ kubernetes.pki.path }}/kube-proxy-key.pem'

- name: Generate Kube Proxy CSR
  openssl_csr:
    path: '{{ kubernetes.pki.path }}/kube-proxy.csr'
    privatekey_path: '{{ kubernetes.pki.path }}/kube-proxy-key.pem'
    basic_constraints: "CA:FALSE"
    basic_constraints_critical: True
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: True
    extended_key_usage:
      - serverAuth
      - clientAuth
    common_name: 'system:kube-proxy'
    organization_name: 'system:node-proxier'
    organizational_unit_name: 'k8s the hard way'
 
- name: Generate Kube Proxy certificate
  openssl_certificate:
    path: '{{ kubernetes.pki.path }}/kube-proxy.pem'
    csr_path: '{{ kubernetes.pki.path }}/kube-proxy.csr'
    ownca_path: '{{ kubernetes.pki.path }}/ca.pem'
    ownca_privatekey_path: '{{ kubernetes.pki.path }}/ca-key.pem'
    provider: ownca
