- name: Generate kube-scheduler private key
  openssl_privatekey:
    path: '{{ kubernetes.pki.path }}/kube-scheduler-key.pem'

- name: Generate kube-scheduler CSR
  openssl_csr:
    path: '{{ kubernetes.pki.path }}/kube-scheduler.csr'
    privatekey_path: '{{ kubernetes.pki.path }}/kube-scheduler-key.pem'
    basic_constraints: "CA:FALSE"
    basic_constraints_critical: True
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: True
    extended_key_usage:
      - serverAuth
      - clientAuth
    common_name: k8s-kube-scheduler
    organization_name: "system:masters"
    organizational_unit_name: k8s the hard way

- name: Generate kube-scheduler certificate
  openssl_certificate:
    path: '{{ kubernetes.pki.path }}/kube-scheduler.pem'
    csr_path: '{{ kubernetes.pki.path }}/kube-scheduler.csr'
    ownca_path: '{{ kubernetes.pki.path }}/ca.pem'
    ownca_privatekey_path: '{{ kubernetes.pki.path }}/ca-key.pem'
    provider: ownca
