- name: Generate service-account private key
  openssl_privatekey:
    path: '{{ kubernetes.pki.path }}/service-account-key.pem'

- name: Generate service-account CSR
  openssl_csr:
    path: '{{ kubernetes.pki.path }}/service-account.csr'
    privatekey_path: '{{ kubernetes.pki.path }}/service-account-key.pem'
    basic_constraints: "CA:FALSE"
    basic_constraints_critical: True
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: True
    extended_key_usage:
      - serverAuth
      - clientAuth
    common_name: k8s-kubernetes
    organization_name: "system:masters"
    organizational_unit_name: k8s the hard way

- name: Generate service-account certificate
  openssl_certificate:
    path: '{{ kubernetes.pki.path }}/service-account.pem'
    csr_path: '{{ kubernetes.pki.path }}/service-account.csr'
    ownca_path: '{{ kubernetes.pki.path }}/ca.pem'
    ownca_privatekey_path: '{{ kubernetes.pki.path }}/ca-key.pem'
    provider: ownca
