- name: Install required packages for containerd
  yum:
    name:
      - unzip
      - tar
      - libseccomp
      - util-linux
      - socat
    state: present

- name: Download containerd
  unarchive:
    src: "https://storage.googleapis.com/cri-containerd-release/cri-containerd-{{ kubernetes.versions.containerd }}.linux-amd64.tar.gz"
    dest: /
    remote_src: yes

- name: Create dir for binaries
  file:
    path: /opt/cni/bin
    state: directory

- name: Create dir for config
  file:
    path: /opt/cni/net.d/
    state: directory

- name: Systemd
  copy:
    src: containerd.service
    dest: /etc/systemd/system/containerd.service

- name: reload systemd config files
  systemd:
    daemon_reload: yes

- name: start and enable containerd
  systemd:
    name: containerd
    state: started
    enabled: yes
